services:
  python-app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: python-app
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - sessions_data:/app/Sessions
      - data:/app/data

volumes:
  sessions_data:
  data:

networks:
  app-network:
    driver: bridge