version: '3.8'

services:
  python-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: python-app
    ports:
      - "8000:8000"
    volumes:
      # Ana dizindeki dosyaları container'a mount ediyoruz
      - ../:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
