version: '3.8'

services:
  python-app:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: python-app
    # volumes satırını kaldırdık (Coolify storage ile çakışmasın)
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
